### ISSUE TITLE
Scientific suits always define you as a loner, regardless of who you are

### ISSUE THREAD

**Issue by RenanMsV** [RenanMsV/stalker_disguise_azazel_fix#1]
**Сrow Sep 23 2019**
`
Hey hello. In the standard disguise mode, there was a problem when you wore suits (exoskeleton and scientific), you had exoskeletons in order, but scientific suits always define you as a loner, regardless of who you are. That is, if you, for example, are a mercenary, then wearing any scientific suit (even your own), you will become a loner. I honestly tried to understand why this happens, but alas, I did not find any connection. Are there any solutions to this problem?
`

Problem seems to be at:
https://github.com/RenanMsV/stalker_disguise_azazel_fix/blob/acb960b3e25ed96fe25f98ca01ba5237f5cf2a49/gamedata/configs/disguise_customizable.ltx#L34

**Comment by RenanMsV** [comment]
**Сrow Oct 23 2019**
`I found a few more errors: banditmerc_outfit defines you as a mercenary, and CS-1 defines you as a loner. The add-on is imperfect, although it fixes problems with the Azazel mode, and scientific suits have errors that I wrote about earlier.`

Problem seems to be at:

https://github.com/RenanMsV/stalker_disguise_azazel_fix/blob/acb960b3e25ed96fe25f98ca01ba5237f5cf2a49/gamedata/configs/disguise_customizable.ltx#L26-L27

**Comment by RenanMsV** [comment]
This seems to be fixed. Could anyone test and give a feedback? [Download link](https://github.com/RenanMsV/stalker_disguise_azazel_fix/archive/a42cac89133cb83329f22267f211437dc14a2da3.zip)

Except for the CS-1 outfit (described as csky_heavy_outfit [here](https://stalker.fandom.com/wiki/CS-1_body_armor)). I couldnt find it in my game.

**Comment by CrowCrowd** [comment]
Oh hell, I did it, how hard it was to register for me here, for I am from Russia. In general, I completely tested all the costumes, and everything began to work as it should, no doubt, and cs -1 it was a suit with the cs_light_novice_outfit section and after the correction it began to work correctly. You can update the add-on on ModDB.

**Comment by RenanMsV** [comment]
Thank you so much for your effort in helping this mod. Good hunting, Stalker!
